# Hiwonder sources, from MDK-ARM/RosRobotControllerM4.uvprojx (133 files),
# minus the two Keil-only ones (RVDS port.c, Hiwonder/Misc/syscall.c).
HIWONDER_C = \
  Core/Src/adc.c \
  Core/Src/crc.c \
  Core/Src/dma.c \
  Core/Src/freertos.c \
  Core/Src/gpio.c \
  Core/Src/i2c.c \
  Core/Src/iwdg.c \
  Core/Src/main.c \
  Core/Src/spi.c \
  Core/Src/stm32f4xx_hal_msp.c \
  Core/Src/stm32f4xx_hal_timebase_tim.c \
  Core/Src/stm32f4xx_it.c \
  Core/Src/system_stm32f4xx.c \
  Core/Src/tim.c \
  Core/Src/usart.c \
  Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_adc.c \
  Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_adc_ex.c \
  Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c \
  Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.c \
  Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_crc.c \
  Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.c \
  Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma_ex.c \
  Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_exti.c \
  Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.c \
  Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.c \
  Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ramfunc.c \
  Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.c \
  Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2c.c \
  Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2c_ex.c \
  Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_iwdg.c \
  Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.c \
  Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr_ex.c \
  Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c \
  Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc_ex.c \
  Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_spi.c \
  Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.c \
  Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex.c \
  Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_uart.c \
  Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_adc.c \
  Hiwonder/Chassis/differential_chassis.c \
  Hiwonder/Chassis/mecanum_chassis.c \
  Hiwonder/Misc/checksum.c \
  Hiwonder/Misc/log.c \
  Hiwonder/Misc/packet.c \
  Hiwonder/Misc/pid.c \
  Hiwonder/Peripherals/button.c \
  Hiwonder/Peripherals/buzzer.c \
  Hiwonder/Peripherals/encoder_motor.c \
  Hiwonder/Peripherals/led.c \
  Hiwonder/Peripherals/pwm_servo.c \
  Hiwonder/Peripherals/QMI8658.c \
  Hiwonder/Peripherals/rgb_spi.c \
  Hiwonder/Peripherals/serial_servo.c \
  Hiwonder/Portings/button_porting.c \
  Hiwonder/Portings/buzzer_porting.c \
  Hiwonder/Portings/chassis_porting.c \
  Hiwonder/Portings/IIC.c \
  Hiwonder/Portings/imu_porting.c \
  Hiwonder/Portings/led_porting.c \
  Hiwonder/Portings/lwmem_porting.c \
  Hiwonder/Portings/motor_porting.c \
  Hiwonder/Portings/packet_porting.c \
  Hiwonder/Portings/pwm_servo_porting.c \
  Hiwonder/Portings/serial_servo_porting.c \
  Hiwonder/Portings/u8g2_porting.c \
  Hiwonder/System/app.c \
  Hiwonder/System/battery_handle.c \
  Hiwonder/System/oled_handle.c \
  Hiwonder/System/packet_handle.c \
  Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/cmsis_os2.c \
  Middlewares/Third_Party/FreeRTOS/Source/croutine.c \
  Middlewares/Third_Party/FreeRTOS/Source/event_groups.c \
  Middlewares/Third_Party/FreeRTOS/Source/list.c \
  Middlewares/Third_Party/FreeRTOS/Source/portable/MemMang/heap_4.c \
  Middlewares/Third_Party/FreeRTOS/Source/queue.c \
  Middlewares/Third_Party/FreeRTOS/Source/stream_buffer.c \
  Middlewares/Third_Party/FreeRTOS/Source/tasks.c \
  Middlewares/Third_Party/FreeRTOS/Source/timers.c \
  Third_Party/Fusion/Fusion/FusionAhrs.c \
  Third_Party/Fusion/Fusion/FusionCompass.c \
  Third_Party/Fusion/Fusion/FusionOffset.c \
  Third_Party/Lw/lwmem.c \
  Third_Party/Lw/lwmem_sys_cmsis_os.c \
  Third_Party/Lw/lwpkt.c \
  Third_Party/Lw/lwrb.c \
  Third_Party/Lw/lwshell.c \
  Third_Party/RTT/SEGGER_RTT.c \
  Third_Party/RTT/SEGGER_RTT_printf.c \
  Third_Party/U8g2/mui.c \
  Third_Party/U8g2/mui_u8g2.c \
  Third_Party/U8g2/u8g2_bitmap.c \
  Third_Party/U8g2/u8g2_box.c \
  Third_Party/U8g2/u8g2_buffer.c \
  Third_Party/U8g2/u8g2_button.c \
  Third_Party/U8g2/u8g2_circle.c \
  Third_Party/U8g2/u8g2_cleardisplay.c \
  Third_Party/U8g2/u8g2_d_memory.c \
  Third_Party/U8g2/u8g2_d_setup.c \
  Third_Party/U8g2/u8g2_font.c \
  Third_Party/U8g2/u8g2_fonts.c \
  Third_Party/U8g2/u8g2_hvline.c \
  Third_Party/U8g2/u8g2_input_value.c \
  Third_Party/U8g2/u8g2_intersection.c \
  Third_Party/U8g2/u8g2_kerning.c \
  Third_Party/U8g2/u8g2_line.c \
  Third_Party/U8g2/u8g2_ll_hvline.c \
  Third_Party/U8g2/u8g2_message.c \
  Third_Party/U8g2/u8g2_polygon.c \
  Third_Party/U8g2/u8g2_selection_list.c \
  Third_Party/U8g2/u8g2_setup.c \
  Third_Party/U8g2/u8log.c \
  Third_Party/U8g2/u8log_u8g2.c \
  Third_Party/U8g2/u8log_u8x8.c \
  Third_Party/U8g2/u8x8_8x8.c \
  Third_Party/U8g2/u8x8_byte.c \
  Third_Party/U8g2/u8x8_cad.c \
  Third_Party/U8g2/u8x8_capture.c \
  Third_Party/U8g2/u8x8_debounce.c \
  Third_Party/U8g2/u8x8_display.c \
  Third_Party/U8g2/u8x8_d_ssd1306_128x32.c \
  Third_Party/U8g2/u8x8_d_ssd1306_128x64_noname.c \
  Third_Party/U8g2/u8x8_d_stdio.c \
  Third_Party/U8g2/u8x8_fonts.c \
  Third_Party/U8g2/u8x8_gpio.c \
  Third_Party/U8g2/u8x8_input_value.c \
  Third_Party/U8g2/u8x8_message.c \
  Third_Party/U8g2/u8x8_selection_list.c \
  Third_Party/U8g2/u8x8_setup.c \
  Third_Party/U8g2/u8x8_string.c \
  Third_Party/U8g2/u8x8_u16toa.c \
  Third_Party/U8g2/u8x8_u8toa.c \

